# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestWebsitesSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_livescore(self):
    self.driver.get("https://www.livescore.com/")
    self.driver.find_element(By.LINK_TEXT, "HOCKEY").click()
    self.driver.find_element(By.LINK_TEXT, "BASKETBALL").click()
    self.driver.find_element(By.LINK_TEXT, "TENNIS").click()
    self.driver.find_element(By.LINK_TEXT, "CRICKET").click()
    self.driver.find_element(By.LINK_TEXT, "MOBILE").click()
    self.driver.find_element(By.LINK_TEXT, "ADVERTISE").click()
    self.driver.find_element(By.LINK_TEXT, "SETTINGS").click()
  
  def test_fleshscore(self):
    self.driver.get("https://strengthsensei.com//")
    self.driver.set_window_size(1280, 738)
    self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(2) > .menuTop__text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(3) > .menuTop__text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(4) > .menuTop__text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(5) > .menuTop__text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(6) > .menuTop__text").click()
  
  def test_clikpic(self):
    self.driver.get("https://www.clikpic.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".autoimagewidth > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_howitworks").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_prices").click()
    self.driver.find_element(By.CSS_SELECTOR, ".first > .section_index").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_featured").click()
    self.driver.find_element(By.CSS_SELECTOR, ".last > .section_styles").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_register").click()
    self.driver.find_element(By.CSS_SELECTOR, "img").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "contentOuter").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
    self.driver.find_element(By.LINK_TEXT, "Terms and conditions").click()
    self.driver.find_element(By.LINK_TEXT, "Terms and conditions").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_howitworks").click()
    self.driver.find_element(By.CSS_SELECTOR, ".first > .section_index").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".first > .section_index").click()
    self.driver.find_element(By.CSS_SELECTOR, "img:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".last > .section_styles").click()
    self.driver.find_element(By.CSS_SELECTOR, ".clear_filter").click()
    self.driver.find_element(By.ID, "ui-id-11").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hp_style_help_helpicon .icon-question").click()
    self.driver.find_element(By.CSS_SELECTOR, "#layout_help_helpicon .icon-question").click()
    self.driver.find_element(By.CSS_SELECTOR, "#style_help_helpicon .icon-question").click()
  
  def test_goal(self):
    self.driver.get("https://www.goal.com/en")
    self.driver.find_element(By.LINK_TEXT, "Live Scores").click()
    self.driver.find_element(By.LINK_TEXT, "Teams").click()
    self.driver.find_element(By.LINK_TEXT, "Betting").click()
    self.driver.find_element(By.CSS_SELECTOR, ".widget-navigation__logo").click()
  
  def test_imdb(self):
    self.driver.get("https://www.imdb.com/")
    self.driver.find_element(By.ID, "home_img").click()
    self.driver.find_element(By.ID, "navbar-submit-button").click()
    self.driver.find_element(By.ID, "imdb-signin-link").click()
    self.driver.find_element(By.LINK_TEXT, "Help").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aok-block").click()
    self.driver.find_element(By.ID, "search_input").click()
    self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
    self.driver.find_element(By.ID, "navTitleMenu").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navCategory img").click()
    self.driver.find_element(By.LINK_TEXT, "Subscriber Agreement").click()
  
  def test_mondo(self):
    self.driver.get("http://mondo.rs/Naslovna")
    self.driver.find_element(By.CSS_SELECTOR, ".nav_zabava > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav_magazin > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".smallText").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav_info > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav_zabava > a").click()
  
  def test_makeuseof(self):
    self.driver.get("https://www.makeuseof.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(5) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sub-menu > .current-menu-item > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(6) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sub-menu:nth-child(1) > .menu-item:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(3) > a").click()
  
  def test_nba(self):
    self.driver.get("https://www.nba.com/#/")
    self.driver.find_element(By.LINK_TEXT, "Scores").click()
    self.driver.find_element(By.LINK_TEXT, "Schedule").click()
    self.driver.find_element(By.CSS_SELECTOR, ".turner-nav__left > .turner-nav__menu-item:nth-child(3) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nba-nav__container--logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nba-nav__container--button").click()
  
  def test_soccer24(self):
    self.driver.get("https://www.soccer24.com/")
    self.driver.find_element(By.LINK_TEXT, "Soccer").click()
    self.driver.find_element(By.LINK_TEXT, "LIVE NOW").click()
    self.driver.find_element(By.LINK_TEXT, "Tennis").click()
    self.driver.find_element(By.LINK_TEXT, "Basketball").click()
    self.driver.find_element(By.LINK_TEXT, "Ice Hockey").click()
  
  def test_udemy(self):
    self.driver.get("https://www.udemy.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".udemy-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, "#header\.browse > span:nth-child(2)").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "header.try-ufb").click()
    self.vars["win506"] = self.wait_for_window(2000)
    self.driver.find_element(By.ID, "header.my-courses").click()
    self.driver.find_element(By.CSS_SELECTOR, ".udemy-logo").click()
  
  def test_ultimateqa(self):
    self.driver.get("https://www.ultimateqa.com/")
    self.driver.find_element(By.ID, "logo").click()
    self.driver.find_element(By.LINK_TEXT, "Blog").click()
    self.driver.find_element(By.LINK_TEXT, "Courses").click()
    self.driver.find_element(By.LINK_TEXT, "All Courses").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-logo__image").click()
    self.driver.find_element(By.LINK_TEXT, "Selenium Resources").click()
    self.driver.find_element(By.NAME, "s").click()
    self.driver.find_element(By.CSS_SELECTOR, ".et_close_search_field").click()
    self.driver.find_element(By.LINK_TEXT, "Automation Exercises").click()
  
  def test_adidas(self):
    self.driver.get("https://www.adidas.com/us")
    self.driver.find_element(By.CSS_SELECTOR, ".glass-navigation-flyout___1AJqi:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover___2eYBD > .label").click()
    self.driver.find_element(By.LINK_TEXT, "NEWSLETTER SIGNUP").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gl-cta--primary > .gl-cta__text").click()
    self.driver.find_element(By.LINK_TEXT, "LOG IN").click()
    self.driver.find_element(By.LINK_TEXT, "adidas").click()
  
  def test_art(self):
    self.driver.get("https://www.art.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".Call-Us > .icon-text").click()
    self.driver.find_element(By.ID, "track-subjects").click()
    self.driver.find_element(By.ID, "track-artist").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cls-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Live-Chat > .icon-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sign-up > div").click()
  
  def test_balloons(self):
    self.driver.get("https://www.balloons.com/")
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.LINK_TEXT, "My Account").click()
    self.driver.find_element(By.LINK_TEXT, "My Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(1) .logo").click()
    self.driver.find_element(By.LINK_TEXT, "Catalogs").click()
    self.driver.find_element(By.LINK_TEXT, "Gifts & Supplies").click()
    self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.LINK_TEXT, "Latex Information").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Privacy & Security").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(40)").click()
  
  def test_bananarepublic(self):
    self.driver.get("https://www.bananarepublic.eu/")
    self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(2) .navigation__category-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(3) .navigation__category-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(4) .navigation__category-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(5) .navigation__category-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(6) .navigation__category-name").click()
  
  def test_bbc(self):
    self.driver.get("https://www.bbc.com/")
    self.driver.find_element(By.LINK_TEXT, "News").click()
    self.driver.find_element(By.LINK_TEXT, "Sport").click()
    self.driver.find_element(By.ID, "idcta-username").click()
    self.driver.find_element(By.CSS_SELECTOR, ".link--primary > span").click()
    self.driver.find_element(By.LINK_TEXT, "13 or over").click()
    self.driver.find_element(By.CSS_SELECTOR, ".scaling-svg__container > .scaling-svg__svg > use").click()
  
  def test_blic(self):
    self.driver.get("https://www.blic.rs/")
    self.driver.find_element(By.CSS_SELECTOR, ".menu__main > ul > li:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu__main > ul > li:nth-child(4) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu__main li:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo img").click()
  
  def test_bloomberg(self):
    self.driver.get("https://strengthsensei.com//europe")
    self.driver.find_element(By.LINK_TEXT, "Menu").click()
    self.driver.find_element(By.CSS_SELECTOR, "#navi-submenu-business .navi-submenu__close").click()
    self.driver.find_element(By.LINK_TEXT, "Bloomberg Terminal Demo Request").click()
    self.driver.find_element(By.LINK_TEXT, "Bloomberg Professional Services").click()
    self.driver.find_element(By.LINK_TEXT, "Support").click()
    self.driver.find_element(By.LINK_TEXT, "Request a demo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bb-that-header__link > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#company_menu_link > span").click()
  
  def test_cars(self):
    self.driver.get("https://www.cars.com/")
    self.driver.find_element(By.LINK_TEXT, "Cars for Sale").click()
    self.driver.find_element(By.LINK_TEXT, "Sell Your Car").click()
    self.driver.find_element(By.LINK_TEXT, "Service & Repair").click()
    self.driver.find_element(By.LINK_TEXT, "Research").click()
    self.driver.find_element(By.ID, "cars-com-logo").click()
  
  def test_coinmarketcap(self):
    self.driver.get("https://coinmarketcap.com/")
    self.driver.find_element(By.LINK_TEXT, "Exchanges").click()
    self.driver.find_element(By.LINK_TEXT, "Watchlist").click()
    self.driver.find_element(By.LINK_TEXT, "View All").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cmc-navbar__menuitem:nth-child(1) > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cmc-navbar__menuitem:nth-child(2) > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cmc-navbar__menuitem:nth-child(3) > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-ellipsis-h").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container > div:nth-child(1) > a > .cmc-logo").click()
  
  def test_cointelegraph(self):
    self.driver.get("https://strengthsensei.com//")
    self.driver.find_element(By.LINK_TEXT, "Explained").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-logo-desktop__link > svg").click()
    self.driver.find_element(By.LINK_TEXT, "Top 10 Cryptocurrencies").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-links-desktop__item:nth-child(2) > .header-links-desktop__item-link").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".header-links-desktop__item:nth-child(3) > .header-links-desktop__item-link").click()
    self.vars["win6233"] = self.wait_for_window(2000)
  
  def test_crypto(self):
    self.driver.get("https://www.crypto.com/en/")
    self.driver.find_element(By.LINK_TEXT, "Wallet").click()
    self.driver.find_element(By.LINK_TEXT, "Cards").click()
    self.driver.find_element(By.LINK_TEXT, "Invest").click()
    self.driver.find_element(By.LINK_TEXT, "Credit").click()
    self.driver.find_element(By.LINK_TEXT, "Support").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__logo img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".g__space:nth-child(1) .t__h3").click()
  
  def test_fox(self):
    self.driver.get("https://www.fox.com/")
    self.driver.find_element(By.LINK_TEXT, "Entertainment").click()
    self.driver.find_element(By.LINK_TEXT, "Sports").click()
    self.driver.find_element(By.LINK_TEXT, "News").click()
    self.driver.find_element(By.LINK_TEXT, "Live TV & Schedule").click()
    self.driver.find_element(By.CSS_SELECTOR, ".NetworkLink_logo_1vCdQ > img").click()
  
  def test_horoskop(self):
    self.driver.get("https://www.horoskop.com/")
    self.driver.find_element(By.LINK_TEXT, "Sternzeichen").click()
    self.driver.find_element(By.LINK_TEXT, "Horoskope").click()
    self.driver.find_element(By.LINK_TEXT, "Wissen").click()
    self.driver.find_element(By.LINK_TEXT, "Esoterik").click()
    self.driver.find_element(By.CSS_SELECTOR, ".breadcrumb > a").click()
    self.driver.find_element(By.ID, "pagespeed_img_4M5XaMGTIk1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".zodiac_inner > div:nth-child(5) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".zodiac_inner > div:nth-child(3) img").click()
  
  def test_malioglasi(self):
    self.driver.get("https://www.malioglasi.com/")
    self.driver.find_element(By.LINK_TEXT, "Informacije").click()
    self.driver.find_element(By.LINK_TEXT, "Kom. oglasi").click()
    self.driver.find_element(By.LINK_TEXT, "Korisnici").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Rubrike").click()
    self.driver.find_element(By.LINK_TEXT, "Slanje oglasa").click()
  
  def test_mobile(self):
    self.driver.get("https://www.mobile.de/")
    self.driver.find_element(By.ID, "quicksearch__SellTab").click()
    self.driver.find_element(By.ID, "quicksearch__BuyTab").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qs-categories:nth-child(4) .gicon-searchbike-xxl").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mde-react-header__main-nav-item:nth-child(1) .font-gibson-semibold").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gicon-mobilede-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hdmylogin > span").click()
  
  def test_nike(self):
    self.driver.get("https://www.nike.com/it/")
    self.driver.find_element(By.LINK_TEXT, "UOMO").click()
    self.driver.find_element(By.LINK_TEXT, "BAMBINI").click()
    self.driver.find_element(By.LINK_TEXT, "PERSONALIZZA").click()
    self.driver.find_element(By.LINK_TEXT, "COLLEZIONI").click()
  
  def test_oneal(self):
    self.driver.get("https://www.oneal.com/")
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-3961 > a > .avia-menu-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-3962 > a > .avia-menu-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-2971 > a > .avia-menu-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-7006 .avia-menu-text").click()
    self.driver.find_element(By.LINK_TEXT, "COMPANY").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo img").click()
  
  def test_petsmart(self):
    self.driver.get("https://www.petsmart.com/")
    self.driver.find_element(By.LINK_TEXT, "shop by brand").click()
    self.driver.find_element(By.LINK_TEXT, "sale").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dp-logo-container img").click()
    self.driver.find_element(By.CSS_SELECTOR, "a > .dp-nav-link").click()
  
  def test_polovniautomobili(self):
    self.driver.get("https://www.polovniautomobili.com/")
    self.driver.find_element(By.LINK_TEXT, "BRZA PRETRAGA").click()
    self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(3) > .icon-cat-29").click()
    self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(4) > .icon-cat-truck").click()
    self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(7) > .icon-cat-3383").click()
    self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(2) > .icon-cat-26").click()
    self.driver.find_element(By.CSS_SELECTOR, ".polovniautomobili-logo-desktop").click()
  
  def test_tattoo(self):
    self.driver.get("https://www.tattoo.com/")
    self.driver.find_element(By.LINK_TEXT, "Artists").click()
    self.driver.find_element(By.LINK_TEXT, "Exclusives").click()
    self.driver.find_element(By.LINK_TEXT, "Music & Entertainment").click()
    self.driver.find_element(By.LINK_TEXT, "Tattoo Articles").click()
    self.driver.find_element(By.LINK_TEXT, "Tattoo Photos").click()
  
  def test_yahoo(self):
    self.driver.get("https://www.yahoo.com/")
    self.driver.find_element(By.LINK_TEXT, "Sports").click()
    self.driver.find_element(By.LINK_TEXT, "Entertainment").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Fw\(400\)").click()
    self.driver.find_element(By.ID, "uh-logo").click()
  
  def test_mojauto(self):
    self.driver.get("https://www.mojauto.rs/")
    self.driver.find_element(By.CSS_SELECTOR, "#hm_101 > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hm_102 span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hm_107 span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hm_103 > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#hm_108 span").click()
  
  def test_alltop(self):
    self.driver.get("https://alltop.com/")
    self.driver.find_element(By.LINK_TEXT, "Viral").click()
    self.driver.find_element(By.LINK_TEXT, "Sports").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Other").click()
    self.driver.find_element(By.LINK_TEXT, "Business").click()
    self.driver.find_element(By.LINK_TEXT, "Lifestyle").click()
    self.driver.find_element(By.LINK_TEXT, "Entertainment").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "AllTop").click()
  
  def test_bigcommerce(self):
    self.driver.get("https://www.bigcommerce.com/")
    self.driver.find_element(By.LINK_TEXT, "Solutions").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tabs-tab:nth-child(2) > .tab-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".title-area-logo").click()
    self.driver.find_element(By.LINK_TEXT, "Help Center").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__contact__show-trigger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__logo-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".popover__head-close-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__logo-icon").click()
  
  def test_collegehumor(self):
    self.driver.get("http://www.collegehumor.com/")
    self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
    self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
    self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
    self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
    self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
    self.driver.find_element(By.CSS_SELECTOR, ".site-header__trigger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comics > .site-nav__item-link").click()
    self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
  
  def test_eatliver(self):
    self.driver.get("https://www.eatliver.com/")
    self.driver.find_element(By.LINK_TEXT, "Latest Posts").click()
    self.driver.find_element(By.LINK_TEXT, "Random Post").click()
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo1 img").click()
  
  def test_fiba(self):
    self.driver.get("https://www.fiba.basketball/")
    self.driver.find_element(By.LINK_TEXT, "FIBA.basketball").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "World Cup").click()
    self.vars["win7315"] = self.wait_for_window(2000)
    self.driver.find_element(By.LINK_TEXT, "FIBA.basketball").click()
    self.driver.find_element(By.LINK_TEXT, "Media Centre").click()
  
  def test_fifa(self):
    self.driver.get("https://www.fifa.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".fi-main-menu > li:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fi-site-brand__logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fi-main-menu > li:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fi-site-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "News").click()
  
  def test_fiverr(self):
    self.driver.get("https://www.fiverr.com/")
    self.driver.find_element(By.LINK_TEXT, "Become a Seller").click()
    self.driver.find_element(By.CSS_SELECTOR, ".site-logo").click()
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Become a Seller").click()
    self.driver.find_element(By.LINK_TEXT, "Join").click()
  
  def test_kupujemprodajem(self):
    self.driver.get("https://www.kupujemprodajem.com/")
    self.driver.find_element(By.LINK_TEXT, "Najnoviji").click()
    self.driver.find_element(By.LINK_TEXT, "Pretraži detaljno").click()
    self.driver.find_element(By.LINK_TEXT, "Početna").click()
    self.driver.find_element(By.LINK_TEXT, "Promocije oglasa").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo > img").click()
  
  def test_lakodoposla(self):
    self.driver.get("https://www.lakodoposla.com/")
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .pngfix").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > img").click()
    self.driver.find_element(By.LINK_TEXT, "Kontakt").click()
    self.driver.find_element(By.LINK_TEXT, "Pitanja i odgovori").click()
    self.driver.find_element(By.LINK_TEXT, "O nama").click()
  
  def test_lifewire(self):
    self.driver.get("https://www.lifewire.com/")
    self.driver.find_element(By.LINK_TEXT, "HOW TO").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 use").click()
    self.driver.find_element(By.LINK_TEXT, "FIX").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 use").click()
    self.driver.find_element(By.ID, "general-search-search-input").click()
    self.driver.find_element(By.LINK_TEXT, "BUY").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 > .icon").click()
    self.driver.find_element(By.LINK_TEXT, "DO MORE").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 > .icon").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.LINK_TEXT, "Who We Are").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 use").click()
  
  def test_oberlo(self):
    self.driver.get("https://www.oberlo.com/")
    self.driver.find_element(By.LINK_TEXT, "Features").click()
    self.driver.find_element(By.LINK_TEXT, "Pricing").click()
    self.driver.find_element(By.CSS_SELECTOR, ".site-logo > use").click()
    self.driver.find_element(By.LINK_TEXT, "Blog").click()
    self.driver.find_element(By.LINK_TEXT, "Success Stories").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.vars["win3865"] = self.wait_for_window(2000)
  
  def test_pcworld(self):
    self.driver.get("https://www.pcworld.com/")
    self.driver.find_element(By.ID, "whatsHotNav").click()
    self.driver.find_element(By.ID, "reviewsNav").click()
    self.driver.find_element(By.ID, "howtoNav").click()
    self.driver.find_element(By.ID, "logoImage").click()
    self.driver.find_element(By.ID, "whatsHotNav").click()
  
  def test_quicksuport(self):
    self.driver.get("https://www.quicksprout.com/")
    self.driver.find_element(By.LINK_TEXT, "Create a Website").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43949 > .sf-with-ul > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43953 > .sf-with-ul > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43958 > .sf-with-ul > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43963 > .sf-with-ul > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43965 span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-logo").click()
    self.driver.find_element(By.LINK_TEXT, "Create a Website").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-logo").click()
    self.driver.find_element(By.LINK_TEXT, "Ecommerce").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-logo").click()
    self.driver.find_element(By.ID, "start_now_btn").click()
  
  def test_valentino(self):
    self.driver.get("https://www.valentino.com/en-rs/")
    self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(1) > div > .text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(2) > div > .text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(3) > div > .text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(4) > div > .text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".TOP .text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".svg-logo").click()
  
  def test_ultimatetennisstatistics(self):
    self.driver.get("https://www.ultimatetennisstatistics.com/")
    self.driver.find_element(By.LINK_TEXT, "GOAT List").click()
    self.driver.find_element(By.LINK_TEXT, "Records").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand span:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Rivalries").click()
    self.driver.find_element(By.LINK_TEXT, "Rivalries").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-cog").click()
  
  def test_deadspin(self):
    self.driver.get("https://deadspin.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".networknav__active-blogname > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(6) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(5) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gmg-logo").click()
  
  def test_npr(self):
    self.driver.get("https://www.npr.org/")
    self.driver.find_element(By.CSS_SELECTOR, ".menu__item--news > .menu__item-inner > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu__item--arts-life > .menu__item-inner > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu__item--music > .menu__item-inner > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu__item--shows-podcasts > .menu__item-inner > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navigation__home img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#user-account-dropdown-mount .user-account__sign-in").click()
    self.driver.find_element(By.CSS_SELECTOR, "#npr-logo > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu__item--shows-podcasts > .menu__item-inner > a").click()
  
  def test_nytimes(self):
    self.driver.get("https://www.nytimes.com/")
    self.driver.find_element(By.LINK_TEXT, "World").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-nhjhh0 > svg").click()
    self.driver.find_element(By.LINK_TEXT, "U.S.").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-nhjhh0 > svg").click()
    self.driver.find_element(By.LINK_TEXT, "Politics").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-nhjhh0 path").click()
  
  def test_si(self):
    self.driver.get("https://www.si.com/")
    self.driver.find_element(By.LINK_TEXT, "NFL").click()
    self.driver.find_element(By.LINK_TEXT, "NBA").click()
    self.driver.find_element(By.LINK_TEXT, "MLB").click()
    self.driver.find_element(By.CSS_SELECTOR, ".desktop-only:nth-child(2) path").click()
  
  def test_strenghtsensei(self):
    self.driver.get("https://strengthsensei.com/")
    self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(5) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-drop:nth-child(4) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".img-fluid").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-9985 > .nav-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".img-fluid").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(5) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-14007 > .nav-link").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(1) > a").click()
  
  def test_techcrunch(self):
    self.driver.get("https://techcrunch.com/")
    self.driver.find_element(By.LINK_TEXT, "Startups").click()
    self.driver.find_element(By.LINK_TEXT, "Apps").click()
    self.driver.find_element(By.LINK_TEXT, "Gadgets").click()
    self.driver.find_element(By.LINK_TEXT, "Gadgets").click()
    self.driver.find_element(By.ID, "logo-gradient").click()
    self.driver.find_element(By.LINK_TEXT, "Events").click()
    self.driver.find_element(By.ID, "logo-gradient").click()
  
  def test_techmeme(self):
    self.driver.get("https://www.techmeme.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) > .navtabs > a:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logobox img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(7)").click()
  
  def test_thelines(self):
    self.driver.get("https://www.thelines.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".main-navigation .menu-item-4957 > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".main-navigation .menu-item-10492 > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".main-navigation #primary-menu > .menu-item-type-custom > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".main-navigation .menu-item-6662 > a").click()
    self.driver.find_element(By.LINK_TEXT, "DFS").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    self.driver.find_element(By.LINK_TEXT, "DFS").click()
  
  def test_vox(self):
    self.driver.get("https://www.vox.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(4) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(5) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(6) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__logo-large path").click()
    self.driver.find_element(By.LINK_TEXT, "Terms of Use").click()
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__logo-large path:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Company").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-button").click()
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
  
  def test_wired(self):
    self.driver.get("https://www.wired.com/")
    self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--business > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--culture > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--gear > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--ideas > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon--logo").click()
  
