#From S80-100 are scenarios with login functionality and Google queries
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestWebsitesSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()

        self.vars = {}

    def teardown_method(self, method):

        self.driver.quit()


    def wait_for_window(self, timeout = 2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def S1(self):
        self.driver.get("https://www.livescore.com/")
        self.driver.find_element(By.LINK_TEXT, "HOCKEY").click()
        self.driver.find_element(By.LINK_TEXT, "BASKETBALL").click()
        self.driver.find_element(By.LINK_TEXT, "TENNIS").click()
        self.driver.find_element(By.LINK_TEXT, "CRICKET").click()
        self.driver.find_element(By.LINK_TEXT, "MOBILE").click()
        self.driver.find_element(By.LINK_TEXT, "ADVERTISE").click()
        self.driver.find_element(By.LINK_TEXT, "SETTINGS").click()

    def S2(self):
        self.driver.get("https://strengthsensei.com//")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(2) > .menuTop__text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(3) > .menuTop__text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(4) > .menuTop__text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(5) > .menuTop__text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menuTop__item:nth-child(6) > .menuTop__text").click()

    def S3(self):
        self.driver.get("https://www.clikpic.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".autoimagewidth > img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_howitworks").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_prices").click()
        self.driver.find_element(By.CSS_SELECTOR, ".first > .section_index").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_featured").click()
        self.driver.find_element(By.CSS_SELECTOR, ".last > .section_styles").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_register").click()
        self.driver.find_element(By.CSS_SELECTOR, "img").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "contentOuter").click()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.LINK_TEXT, "About us").click()
        self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
        self.driver.find_element(By.LINK_TEXT, "Terms and conditions").click()
        self.driver.find_element(By.LINK_TEXT, "Terms and conditions").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main_menu_menu .section_howitworks").click()
        self.driver.find_element(By.CSS_SELECTOR, ".first > .section_index").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.CSS_SELECTOR, ".first > .section_index").click()
        self.driver.find_element(By.CSS_SELECTOR, "img:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "About us").click()
        self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.CSS_SELECTOR, ".last > .section_styles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".clear_filter").click()
        self.driver.find_element(By.ID, "ui-id-11").click()
        self.driver.find_element(By.CSS_SELECTOR, "#hp_style_help_helpicon .icon-question").click()
        self.driver.find_element(By.CSS_SELECTOR, "#layout_help_helpicon .icon-question").click()
        self.driver.find_element(By.CSS_SELECTOR, "#style_help_helpicon .icon-question").click()

    def S4(self):
        self.driver.get("https://www.goal.com/en")
        self.driver.find_element(By.LINK_TEXT, "Live Scores").click()
        self.driver.find_element(By.LINK_TEXT, "Teams").click()
        self.driver.find_element(By.LINK_TEXT, "Betting").click()
        self.driver.find_element(By.CSS_SELECTOR, ".widget-navigation__logo").click()

    def S5(self):
        self.driver.get("https://www.imdb.com/")
        self.driver.find_element(By.ID, "home_img").click()
        self.driver.find_element(By.ID, "navbar-submit-button").click()
        self.driver.find_element(By.ID, "imdb-signin-link").click()
        self.driver.find_element(By.LINK_TEXT, "Help").click()
        self.driver.find_element(By.CSS_SELECTOR, ".aok-block").click()
        self.driver.find_element(By.ID, "search_input").click()
        self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
        self.driver.find_element(By.ID, "navTitleMenu").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navCategory img").click()
        self.driver.find_element(By.LINK_TEXT, "Subscriber Agreement").click()

    def S6(self):
        self.driver.get("http://mondo.rs/Naslovna")
        self.driver.find_element(By.CSS_SELECTOR, ".nav_zabava > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav_magazin > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".smallText").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav_info > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav_zabava > a").click()

    def S7(self):
        self.driver.get("https://www.makeuseof.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(5) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sub-menu > .current-menu-item > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(6) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sub-menu:nth-child(1) > .menu-item:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-navigation #menu-main-menu > .menu-item:nth-child(3) > a").click()

    def S8(self):
        self.driver.get("https://www.nba.com/#/")
        self.driver.find_element(By.LINK_TEXT, "Scores").click()
        self.driver.find_element(By.LINK_TEXT, "Schedule").click()
        self.driver.find_element(By.CSS_SELECTOR, ".turner-nav__left > .turner-nav__menu-item:nth-child(3) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nba-nav__container--logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nba-nav__container--button").click()

    def S9(self):
        self.driver.get("https://www.soccer24.com/")
        self.driver.find_element(By.LINK_TEXT, "Soccer").click()
        self.driver.find_element(By.LINK_TEXT, "LIVE NOW").click()
        self.driver.find_element(By.LINK_TEXT, "Tennis").click()
        self.driver.find_element(By.LINK_TEXT, "Basketball").click()
        self.driver.find_element(By.LINK_TEXT, "Ice Hockey").click()

    def S10(self):
        self.driver.get("https://www.udemy.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".udemy-logo").click()
        self.driver.find_element(By.CSS_SELECTOR, "#header\.browse > span:nth-child(2)").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.ID, "header.try-ufb").click()
        self.vars["win506"] = self.wait_for_window(2000)
        self.driver.find_element(By.ID, "header.my-courses").click()
        self.driver.find_element(By.CSS_SELECTOR, ".udemy-logo").click()

    def S11(self):
        self.driver.get("https://www.ultimateqa.com/")
        self.driver.find_element(By.ID, "logo").click()
        self.driver.find_element(By.LINK_TEXT, "Blog").click()
        self.driver.find_element(By.LINK_TEXT, "Courses").click()
        self.driver.find_element(By.LINK_TEXT, "All Courses").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-logo__image").click()
        self.driver.find_element(By.LINK_TEXT, "Selenium Resources").click()
        self.driver.find_element(By.NAME, "s").click()
        self.driver.find_element(By.CSS_SELECTOR, ".et_close_search_field").click()
        self.driver.find_element(By.LINK_TEXT, "Automation Exercises").click()

    def S12(self):
        self.driver.get("https://www.adidas.com/us")
        self.driver.find_element(By.CSS_SELECTOR, ".glass-navigation-flyout___1AJqi:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".hover___2eYBD > .label").click()
        self.driver.find_element(By.LINK_TEXT, "NEWSLETTER SIGNUP").click()
        self.driver.find_element(By.CSS_SELECTOR, ".gl-cta--primary > .gl-cta__text").click()
        self.driver.find_element(By.LINK_TEXT, "LOG IN").click()
        self.driver.find_element(By.LINK_TEXT, "adidas").click()

    def S13(self):
        self.driver.get("https://www.art.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".Call-Us > .icon-text").click()
        self.driver.find_element(By.ID, "track-subjects").click()
        self.driver.find_element(By.ID, "track-artist").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cls-1").click()
        self.driver.find_element(By.CSS_SELECTOR, ".Live-Chat > .icon-text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sign-up > div").click()

    def S14(self):
        self.driver.get("https://www.balloons.com/")
        self.driver.find_element(By.LINK_TEXT, "About Us").click()
        self.driver.find_element(By.LINK_TEXT, "My Account").click()
        self.driver.find_element(By.LINK_TEXT, "My Cart").click()
        self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(1) .logo").click()
        self.driver.find_element(By.LINK_TEXT, "Catalogs").click()
        self.driver.find_element(By.LINK_TEXT, "Gifts & Supplies").click()
        self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.LINK_TEXT, "Latex Information").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Privacy & Security").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(40)").click()

    def S15(self):
        self.driver.get("https://www.bananarepublic.eu/")
        self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(2) .navigation__category-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(3) .navigation__category-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(4) .navigation__category-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(5) .navigation__category-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navigation__item:nth-child(6) .navigation__category-name").click()

    def S16(self):
        self.driver.get("https://www.bbc.com/")
        self.driver.find_element(By.LINK_TEXT, "News").click()
        self.driver.find_element(By.LINK_TEXT, "Sport").click()
        self.driver.find_element(By.ID, "idcta-username").click()
        self.driver.find_element(By.CSS_SELECTOR, ".link--primary > span").click()
        self.driver.find_element(By.LINK_TEXT, "13 or over").click()
        self.driver.find_element(By.CSS_SELECTOR, ".scaling-svg__container > .scaling-svg__svg > use").click()

    def S17(self):
        self.driver.get("https://www.blic.rs/")
        self.driver.find_element(By.CSS_SELECTOR, ".menu__main > ul > li:nth-child(3) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menu__main > ul > li:nth-child(4) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menu__main li:nth-child(2) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo img").click()

    def S18(self):
        self.driver.get("https://strengthsensei.com//europe")
        self.driver.find_element(By.LINK_TEXT, "Menu").click()
        self.driver.find_element(By.CSS_SELECTOR, "#navi-submenu-business .navi-submenu__close").click()
        self.driver.find_element(By.LINK_TEXT, "Bloomberg Terminal Demo Request").click()
        self.driver.find_element(By.LINK_TEXT, "Bloomberg Professional Services").click()
        self.driver.find_element(By.LINK_TEXT, "Support").click()
        self.driver.find_element(By.LINK_TEXT, "Request a demo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".bb-that-header__link > span:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#company_menu_link > span").click()

    def S19(self):
        self.driver.get("https://www.cars.com/")
        self.driver.find_element(By.LINK_TEXT, "Cars for Sale").click()
        self.driver.find_element(By.LINK_TEXT, "Sell Your Car").click()
        self.driver.find_element(By.LINK_TEXT, "Service & Repair").click()
        self.driver.find_element(By.LINK_TEXT, "Research").click()
        self.driver.find_element(By.ID, "cars-com-logo").click()

    def S20(self):
        self.driver.get("https://coinmarketcap.com/")
        self.driver.find_element(By.LINK_TEXT, "Exchanges").click()
        self.driver.find_element(By.LINK_TEXT, "Watchlist").click()
        self.driver.find_element(By.LINK_TEXT, "View All").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cmc-navbar__menuitem:nth-child(1) > div:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cmc-navbar__menuitem:nth-child(2) > div:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cmc-navbar__menuitem:nth-child(3) > div:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".icon-ellipsis-h").click()
        self.driver.find_element(By.CSS_SELECTOR, ".container > div:nth-child(1) > a > .cmc-logo").click()

    def S21(self):
        self.driver.get("https://strengthsensei.com//")
        self.driver.find_element(By.LINK_TEXT, "Explained").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-logo-desktop__link > svg").click()
        self.driver.find_element(By.LINK_TEXT, "Top 10 Cryptocurrencies").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-links-desktop__item:nth-child(2) > .header-links-desktop__item-link").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".header-links-desktop__item:nth-child(3) > .header-links-desktop__item-link").click()
        self.vars["win6233"] = self.wait_for_window(2000)

    def S22(self):
        self.driver.get("https://www.crypto.com/en/")
        self.driver.find_element(By.LINK_TEXT, "Wallet").click()
        self.driver.find_element(By.LINK_TEXT, "Cards").click()
        self.driver.find_element(By.LINK_TEXT, "Invest").click()
        self.driver.find_element(By.LINK_TEXT, "Credit").click()
        self.driver.find_element(By.LINK_TEXT, "Support").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__logo img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".g__space:nth-child(1) .t__h3").click()

    def S23(self):
        self.driver.get("https://www.fox.com/")
        self.driver.find_element(By.LINK_TEXT, "Entertainment").click()
        self.driver.find_element(By.LINK_TEXT, "Sports").click()
        self.driver.find_element(By.LINK_TEXT, "News").click()
        self.driver.find_element(By.LINK_TEXT, "Live TV & Schedule").click()
        self.driver.find_element(By.CSS_SELECTOR, ".NetworkLink_logo_1vCdQ > img").click()

    def S24(self):
        self.driver.get("https://www.horoskop.com/")
        self.driver.find_element(By.LINK_TEXT, "Sternzeichen").click()
        self.driver.find_element(By.LINK_TEXT, "Horoskope").click()
        self.driver.find_element(By.LINK_TEXT, "Wissen").click()
        self.driver.find_element(By.LINK_TEXT, "Esoterik").click()
        self.driver.find_element(By.CSS_SELECTOR, ".breadcrumb > a").click()
        self.driver.find_element(By.ID, "pagespeed_img_4M5XaMGTIk1").click()
        self.driver.find_element(By.CSS_SELECTOR, ".zodiac_inner > div:nth-child(5) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".zodiac_inner > div:nth-child(3) img").click()

    def S25(self):
        self.driver.get("https://www.malioglasi.com/")
        self.driver.find_element(By.LINK_TEXT, "Informacije").click()
        self.driver.find_element(By.LINK_TEXT, "Kom. oglasi").click()
        self.driver.find_element(By.LINK_TEXT, "Korisnici").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Rubrike").click()
        self.driver.find_element(By.LINK_TEXT, "Slanje oglasa").click()

    def S26(self):
        self.driver.get("https://www.mobile.de/")
        self.driver.find_element(By.ID, "quicksearch__SellTab").click()
        self.driver.find_element(By.ID, "quicksearch__BuyTab").click()
        self.driver.find_element(By.CSS_SELECTOR, ".qs-categories:nth-child(4) .gicon-searchbike-xxl").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mde-react-header__main-nav-item:nth-child(1) .font-gibson-semibold").click()
        self.driver.find_element(By.CSS_SELECTOR, ".gicon-mobilede-logo").click()
        self.driver.find_element(By.CSS_SELECTOR, "#hdmylogin > span").click()

    def S27(self):
        self.driver.get("https://www.nike.com/it/")
        self.driver.find_element(By.LINK_TEXT, "UOMO").click()
        self.driver.find_element(By.LINK_TEXT, "BAMBINI").click()
        self.driver.find_element(By.LINK_TEXT, "PERSONALIZZA").click()
        self.driver.find_element(By.LINK_TEXT, "COLLEZIONI").click()

    def S28(self):
        self.driver.get("https://www.oneal.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-3961 > a > .avia-menu-text").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-3962 > a > .avia-menu-text").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-2971 > a > .avia-menu-text").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-7006 .avia-menu-text").click()
        self.driver.find_element(By.LINK_TEXT, "COMPANY").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo img").click()

    def S29(self):
        self.driver.get("https://www.petsmart.com/")
        self.driver.find_element(By.LINK_TEXT, "shop by brand").click()
        self.driver.find_element(By.LINK_TEXT, "sale").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dp-logo-container img").click()
        self.driver.find_element(By.CSS_SELECTOR, "a > .dp-nav-link").click()

    def S30(self):
        self.driver.get("https://www.polovniautomobili.com/")
        self.driver.find_element(By.LINK_TEXT, "BRZA PRETRAGA").click()
        self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(3) > .icon-cat-29").click()
        self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(4) > .icon-cat-truck").click()
        self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(7) > .icon-cat-3383").click()
        self.driver.find_element(By.CSS_SELECTOR, ".table-cell:nth-child(2) > .icon-cat-26").click()
        self.driver.find_element(By.CSS_SELECTOR, ".polovniautomobili-logo-desktop").click()

    def S31(self):
        self.driver.get("https://www.tattoo.com/")
        self.driver.find_element(By.LINK_TEXT, "Artists").click()
        self.driver.find_element(By.LINK_TEXT, "Exclusives").click()
        self.driver.find_element(By.LINK_TEXT, "Music & Entertainment").click()
        self.driver.find_element(By.LINK_TEXT, "Tattoo Articles").click()
        self.driver.find_element(By.LINK_TEXT, "Tattoo Photos").click()

    def S32(self):
        self.driver.get("https://www.yahoo.com/")
        self.driver.find_element(By.LINK_TEXT, "Sports").click()
        self.driver.find_element(By.LINK_TEXT, "Entertainment").click()
        self.driver.find_element(By.CSS_SELECTOR, ".Fw\(400\)").click()
        self.driver.find_element(By.ID, "uh-logo").click()

    def S33(self):
        self.driver.get("https://www.mojauto.rs/")
        self.driver.find_element(By.CSS_SELECTOR, "#hm_101 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#hm_102 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#hm_107 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#hm_103 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#hm_108 span").click()

    def S34(self):
        self.driver.get("https://alltop.com/")
        self.driver.find_element(By.LINK_TEXT, "Viral").click()
        self.driver.find_element(By.LINK_TEXT, "Sports").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Other").click()
        self.driver.find_element(By.LINK_TEXT, "Business").click()
        self.driver.find_element(By.LINK_TEXT, "Lifestyle").click()
        self.driver.find_element(By.LINK_TEXT, "Entertainment").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "AllTop").click()

    def S35(self):
        self.driver.get("https://www.bigcommerce.com/")
        self.driver.find_element(By.LINK_TEXT, "Solutions").click()
        self.driver.find_element(By.CSS_SELECTOR, ".tabs-tab:nth-child(2) > .tab-link").click()
        self.driver.find_element(By.CSS_SELECTOR, ".title-area-logo").click()
        self.driver.find_element(By.LINK_TEXT, "Help Center").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__contact__show-trigger").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__nav-link").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__logo-icon").click()
        self.driver.find_element(By.CSS_SELECTOR, ".popover__head-close-btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__logo-icon").click()

    def S36(self):
        self.driver.get("http://www.collegehumor.com/")
        self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
        self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
        self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
        self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
        self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()
        self.driver.find_element(By.CSS_SELECTOR, ".site-header__trigger").click()
        self.driver.find_element(By.CSS_SELECTOR, ".comics > .site-nav__item-link").click()
        self.driver.find_element(By.LINK_TEXT, "CollegeHumor").click()

    def S37(self):
        self.driver.get("https://www.eatliver.com/")
        self.driver.find_element(By.LINK_TEXT, "Latest Posts").click()
        self.driver.find_element(By.LINK_TEXT, "Random Post").click()
        self.driver.find_element(By.LINK_TEXT, "About").click()
        self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo1 img").click()

    def S38(self):
        self.driver.get("https://www.fiba.basketball/")
        self.driver.find_element(By.LINK_TEXT, "FIBA.basketball").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "World Cup").click()
        self.vars["win7315"] = self.wait_for_window(2000)
        self.driver.find_element(By.LINK_TEXT, "FIBA.basketball").click()
        self.driver.find_element(By.LINK_TEXT, "Media Centre").click()

    def S39(self):
        self.driver.get("https://www.fifa.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".fi-main-menu > li:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fi-site-brand__logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fi-main-menu > li:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fi-site-toggle").click()
        self.driver.find_element(By.LINK_TEXT, "News").click()

    def S40(self):
        self.driver.get("https://www.fiverr.com/")
        self.driver.find_element(By.LINK_TEXT, "Become a Seller").click()
        self.driver.find_element(By.CSS_SELECTOR, ".site-logo").click()
        self.driver.find_element(By.LINK_TEXT, "Sign In").click()
        self.driver.find_element(By.LINK_TEXT, "Become a Seller").click()
        self.driver.find_element(By.LINK_TEXT, "Join").click()

    def S41(self):
        self.driver.get("https://www.kupujemprodajem.com/")
        self.driver.find_element(By.LINK_TEXT, "Najnoviji").click()
        self.driver.find_element(By.LINK_TEXT, "Pretraži detaljno").click()
        self.driver.find_element(By.LINK_TEXT, "Početna").click()
        self.driver.find_element(By.LINK_TEXT, "Promocije oglasa").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo > img").click()

    def S42(self):
        self.driver.get("https://www.lakodoposla.com/")
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .pngfix").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > img").click()
        self.driver.find_element(By.LINK_TEXT, "Kontakt").click()
        self.driver.find_element(By.LINK_TEXT, "Pitanja i odgovori").click()
        self.driver.find_element(By.LINK_TEXT, "O nama").click()

    def S43(self):
        self.driver.get("https://www.lifewire.com/")
        self.driver.find_element(By.LINK_TEXT, "HOW TO").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 use").click()
        self.driver.find_element(By.LINK_TEXT, "FIX").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 use").click()
        self.driver.find_element(By.ID, "general-search-search-input").click()
        self.driver.find_element(By.LINK_TEXT, "BUY").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 > .icon").click()
        self.driver.find_element(By.LINK_TEXT, "DO MORE").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 > .icon").click()
        self.driver.find_element(By.LINK_TEXT, "About Us").click()
        self.driver.find_element(By.LINK_TEXT, "Who We Are").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logo_1-0 use").click()

    def S44(self):
        self.driver.get("https://www.oberlo.com/")
        self.driver.find_element(By.LINK_TEXT, "Features").click()
        self.driver.find_element(By.LINK_TEXT, "Pricing").click()
        self.driver.find_element(By.CSS_SELECTOR, ".site-logo > use").click()
        self.driver.find_element(By.LINK_TEXT, "Blog").click()
        self.driver.find_element(By.LINK_TEXT, "Success Stories").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.vars["win3865"] = self.wait_for_window(2000)

    def S45(self):
        self.driver.get("https://www.pcworld.com/")
        self.driver.find_element(By.ID, "whatsHotNav").click()
        self.driver.find_element(By.ID, "reviewsNav").click()
        self.driver.find_element(By.ID, "howtoNav").click()
        self.driver.find_element(By.ID, "logoImage").click()
        self.driver.find_element(By.ID, "whatsHotNav").click()

    def S46(self):
        self.driver.get("https://www.quicksprout.com/")
        self.driver.find_element(By.LINK_TEXT, "Create a Website").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43949 > .sf-with-ul > span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43953 > .sf-with-ul > span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43958 > .sf-with-ul > span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43963 > .sf-with-ul > span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43965 span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".custom-logo").click()
        self.driver.find_element(By.LINK_TEXT, "Create a Website").click()
        self.driver.find_element(By.CSS_SELECTOR, ".custom-logo").click()
        self.driver.find_element(By.LINK_TEXT, "Ecommerce").click()
        self.driver.find_element(By.CSS_SELECTOR, ".custom-logo").click()
        self.driver.find_element(By.ID, "start_now_btn").click()

    def S47(self):
        self.driver.get("https://www.valentino.com/en-rs/")
        self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(1) > div > .text:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(2) > div > .text:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(3) > div > .text:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".level-0 > .hasChildren:nth-child(4) > div > .text:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".TOP .text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".svg-logo").click()

    def S48(self):
        self.driver.get("https://www.ultimatetennisstatistics.com/")
        self.driver.find_element(By.LINK_TEXT, "GOAT List").click()
        self.driver.find_element(By.LINK_TEXT, "Records").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand span:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Rivalries").click()
        self.driver.find_element(By.LINK_TEXT, "Rivalries").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-cog").click()

    def S49(self):
        self.driver.get("https://deadspin.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(2) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".networknav__active-blogname > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(6) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(5) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".gmg-logo").click()

    def S50(self):
        self.driver.get("https://www.npr.org/")
        self.driver.find_element(By.CSS_SELECTOR, ".menu__item--news > .menu__item-inner > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menu__item--arts-life > .menu__item-inner > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menu__item--music > .menu__item-inner > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menu__item--shows-podcasts > .menu__item-inner > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navigation__home img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#user-account-dropdown-mount .user-account__sign-in").click()
        self.driver.find_element(By.CSS_SELECTOR, "#npr-logo > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".menu__item--shows-podcasts > .menu__item-inner > a").click()

    def S51(self):
        self.driver.get("https://www.nytimes.com/")
        self.driver.find_element(By.LINK_TEXT, "World").click()
        self.driver.find_element(By.CSS_SELECTOR, ".css-nhjhh0 > svg").click()
        self.driver.find_element(By.LINK_TEXT, "U.S.").click()
        self.driver.find_element(By.CSS_SELECTOR, ".css-nhjhh0 > svg").click()
        self.driver.find_element(By.LINK_TEXT, "Politics").click()
        self.driver.find_element(By.CSS_SELECTOR, ".css-nhjhh0 path").click()

    def S52(self):
        self.driver.get("https://www.si.com/")
        self.driver.find_element(By.LINK_TEXT, "NFL").click()
        self.driver.find_element(By.LINK_TEXT, "NBA").click()
        self.driver.find_element(By.LINK_TEXT, "MLB").click()
        self.driver.find_element(By.CSS_SELECTOR, ".desktop-only:nth-child(2) path").click()

    def S53(self):
        self.driver.get("https://strengthsensei.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(3) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(5) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".has-drop:nth-child(4) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".img-fluid").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(3) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-9985 > .nav-link").click()
        self.driver.find_element(By.CSS_SELECTOR, ".img-fluid").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(5) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-14007 > .nav-link").click()
        self.driver.find_element(By.CSS_SELECTOR, "#main-menu > li:nth-child(1) > a").click()

    def S54(self):
        self.driver.get("https://techcrunch.com/")
        self.driver.find_element(By.LINK_TEXT, "Startups").click()
        self.driver.find_element(By.LINK_TEXT, "Apps").click()
        self.driver.find_element(By.LINK_TEXT, "Gadgets").click()
        self.driver.find_element(By.LINK_TEXT, "Gadgets").click()
        self.driver.find_element(By.ID, "logo-gradient").click()
        self.driver.find_element(By.LINK_TEXT, "Events").click()
        self.driver.find_element(By.ID, "logo-gradient").click()

    def S55(self):
        self.driver.get("https://www.techmeme.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) > .navtabs > a:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(4)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logobox img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar:nth-child(3) a:nth-child(7)").click()

    def S56(self):
        self.driver.get("https://www.thelines.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".main-navigation .menu-item-4957 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-navigation .menu-item-10492 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-navigation #primary-menu > .menu-item-type-custom > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-navigation .menu-item-6662 > a").click()
        self.driver.find_element(By.LINK_TEXT, "DFS").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
        self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
        self.driver.find_element(By.LINK_TEXT, "DFS").click()

    def S57(self):
        self.driver.get("https://www.vox.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(2) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(3) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(4) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(5) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__link:nth-child(6) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__logo-large path").click()
        self.driver.find_element(By.LINK_TEXT, "Terms of Use").click()
        self.driver.find_element(By.LINK_TEXT, "Contact").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-global-header__logo-large path:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Company").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-button").click()
        self.driver.find_element(By.LINK_TEXT, "Contact").click()

    def S58(self):
        self.driver.get("https://www.wired.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--business > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--culture > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--gear > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__nav--links .nav--ideas > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".icon--logo").click()

    def S59(self):
        self.driver.get("https://www.12minuteathlete.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-28 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27335 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27778 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".site-logo img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-22 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-28333 > a").click()

    def S60(self):
        self.driver.get("https://breakingmuscle.com/")
        self.driver.find_element(By.LINK_TEXT, "Fitness").click()
        self.driver.find_element(By.LINK_TEXT, "Workouts").click()
        self.driver.find_element(By.LINK_TEXT, "Healthy Eating").click()
        self.driver.find_element(By.LINK_TEXT, "Coaches & Trainers").click()
        self.driver.find_element(By.LINK_TEXT, "Athletics").click()
        self.driver.find_element(By.LINK_TEXT, "Business").click()
        self.driver.find_element(By.ID, "logospace").click()
        self.driver.find_element(By.LINK_TEXT, "Write for Us |").click()
        self.driver.find_element(By.LINK_TEXT, "Contributing Coaches |").click()
        self.driver.find_element(By.LINK_TEXT, "Shop").click()
        self.driver.find_element(By.LINK_TEXT, "Whiteboard").click()
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        self.driver.find_element(By.ID, "logospace").click()

    def S61(self):
        self.driver.get("https://www.cocokelley.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27508 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27514 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27520 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27521 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27506 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27507 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27506 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27522 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27530 > a").click()
        self.driver.find_element(By.LINK_TEXT, "DIY").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-27514 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()

    def S62(self):
        self.driver.get("https://www.dumblittleman.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-top-menu-1 > .menu-item-first > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-top-menu-1 > .menu-item-12504 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-top-menu-1 > .menu-item-2538 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-top-menu-1 > .menu-item-12975 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".td-menu-item:nth-child(5) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".td-main-logo > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".td-menu-item:nth-child(7) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".td-menu-item font").click()
        self.driver.find_element(By.CSS_SELECTOR, ".td-main-logo > img").click()
        self.driver.find_element(By.LINK_TEXT, "2").click()

    def S63(self):
        self.driver.get("https://www.flippingheck.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-11956 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-11974 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-11963 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-11970 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-11978 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#MainHeaderImage img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-16558 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-16558 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-11947 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-14240 > a").click()

    def S64(self):
        self.driver.get("https://www.getrichslowly.org/")
        self.driver.find_element(By.CSS_SELECTOR, ".jdmenu > a:nth-child(4)").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".jdmenu > a:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".jdmenu > a:nth-child(7)").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),\'Archives\')]").click()
        self.driver.find_element(By.LINK_TEXT, "Get Rich Slowly").click()
        self.driver.find_element(By.LINK_TEXT, "Get Rich Slowly").click()
        self.driver.find_element(By.CSS_SELECTOR, ".jdmenu > a:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".jdmenu > a:nth-child(2)").click()

    def S65(self):
        self.driver.get("https://lifehacker.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(2) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(3) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(4) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(5) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".gmg-logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(6) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dfwuc8-0:nth-child(8) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".gmg-logo").click()

    def S66(self):
        self.driver.get("http://www.marcandangel.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-849 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-851 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-3731 span").click()
        self.driver.find_element(By.LINK_TEXT, "PRIVACY POLICY").click()
        self.driver.find_element(By.LINK_TEXT, "PRIVACY POLICY").click()
        self.driver.find_element(By.CSS_SELECTOR, ".OPF__modal-form__close-button").click()
        self.driver.find_element(By.LINK_TEXT, "TERMS POLICY").click()
        self.driver.find_element(By.CSS_SELECTOR, "#p2c8380f104__default .OPF__modal-form__close-button").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cl").click()

    def S67(self):
        self.driver.get("https://mennohenselmans.com/")
        self.driver.find_element(By.LINK_TEXT, "Articles & more").click()
        self.driver.find_element(By.LINK_TEXT, "Online PT courses").click()
        self.driver.find_element(By.LINK_TEXT, "Online coaching").click()
        self.driver.find_element(By.LINK_TEXT, "About").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-branding__logo").click()
        self.driver.find_element(By.LINK_TEXT, "All articles").click()
        self.driver.find_element(By.CSS_SELECTOR, "a > span").click()
        self.driver.find_element(By.LINK_TEXT, "Articles & more").click()
        self.driver.find_element(By.LINK_TEXT, "Physique coaching by Menno").click()
        self.driver.find_element(By.LINK_TEXT, "Articles & more").click()
        self.driver.find_element(By.LINK_TEXT, "Articles & more").click()
        self.driver.find_element(By.LINK_TEXT, "About").click()
        self.driver.find_element(By.LINK_TEXT, "Online coaching").click()
        self.driver.find_element(By.LINK_TEXT, "Online PT courses").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-branding__logo").click()
        self.driver.find_element(By.LINK_TEXT, "Articles & more").click()
        self.driver.find_element(By.LINK_TEXT, "About").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-branding__logo").click()
        self.driver.find_element(By.LINK_TEXT, "Articles & more").click()
        self.driver.find_element(By.LINK_TEXT, "Online PT courses").click()
        self.driver.find_element(By.LINK_TEXT, "Videos & podcasts").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-branding__logo").click()

    def S68(self):
        self.driver.get("https://www.nerdfitness.com/")
        self.driver.find_element(By.LINK_TEXT, "Join the Academy").click()
        self.driver.find_element(By.LINK_TEXT, "Terms and Conditions").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-image-logo").click()
        self.driver.find_element(By.LINK_TEXT, "All Courses").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-image-logo").click()
        self.driver.find_element(By.LINK_TEXT, "About NF").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-image-logo").click()
        self.driver.find_element(By.LINK_TEXT, "Private Coaching").click()

    def S69(self):
        self.driver.get("http://www.productivity501.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8126 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8127 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8129 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8130 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8238 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8128 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8240 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8241 > .sf-with-ul > span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8239 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8125 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8242 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8128 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8126 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8128 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8239 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8244 > .sf-with-ul > span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8242 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8238 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8131 span").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8125 > a").click()
        self.driver.find_element(By.LINK_TEXT, "Productivity501").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-8126 span").click()

    def S70(self):
        self.driver.get("https://www.summertomato.com/")
        self.driver.find_element(By.LINK_TEXT, "Shop").click()
        self.driver.find_element(By.LINK_TEXT, "Contact").click()
        self.driver.find_element(By.LINK_TEXT, "About").click()
        self.driver.find_element(By.LINK_TEXT, "Summer Tomato").click()
        self.driver.find_element(By.LINK_TEXT, "Contact").click()
        self.driver.find_element(By.CSS_SELECTOR, ".column2 > li:nth-child(4) > a").click()
        self.driver.find_element(By.LINK_TEXT, "Summer Tomato").click()
        self.driver.find_element(By.CSS_SELECTOR, ".column3 > li:nth-child(3) > a").click()
        self.driver.find_element(By.LINK_TEXT, "Weight").click()
        self.driver.find_element(By.LINK_TEXT, "Summer Tomato").click()
        self.driver.find_element(By.LINK_TEXT, "Summer Tomato").click()

    def S71(self):
        self.driver.get("http://digg.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".channel__subnav__nav-item-abbrev-truncate").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ico-digg-logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".channel__subnav__nav-item:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ico-digg-logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".channel__subnav__nav-item:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ico-digg-logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".channel__subnav__nav-item:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ico-digg-logo > path").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-login").click()
        self.driver.find_element(By.CSS_SELECTOR, ".digg-logo").click()

    def S72(self):
        self.driver.get("https://www.eonline.com/")
        self.driver.find_element(By.LINK_TEXT, "LATEST NEWS").click()
        self.driver.find_element(By.LINK_TEXT, "ROYALS").click()
        self.driver.find_element(By.LINK_TEXT, "KARDASHIANS").click()
        self.driver.find_element(By.LINK_TEXT, "PHOTOS").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav__logo-link").click()
        self.driver.find_element(By.LINK_TEXT, "LATEST NEWS").click()
        self.driver.find_element(By.LINK_TEXT, "WATCH FULL EPISODES").click()
        self.driver.find_element(By.CSS_SELECTOR, ".desktop").click()
        self.driver.find_element(By.CSS_SELECTOR, ".pullRight .ng-scope").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".helperLink > .link").click()
        self.vars["win6104"] = self.wait_for_window(2000)
        self.driver.find_element(By.CSS_SELECTOR, ".mainHeaderLinks .scheduleLink").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mainHeaderLinks .expandable").click()
        self.driver.find_element(By.CSS_SELECTOR, ".desktop").click()
        self.driver.find_element(By.CSS_SELECTOR, ".pullRight .ng-scope").click()

    def S73(self):
        self.driver.get("http://www.histats.com/")
        self.driver.find_element(By.LINK_TEXT, "FEATURES").click()
        self.driver.find_element(By.LINK_TEXT, "COUNTERS").click()
        self.driver.find_element(By.LINK_TEXT, "HOME").click()
        self.driver.find_element(By.LINK_TEXT, "HELP").click()
        self.driver.find_element(By.ID, "div_LOADINGDIV").click()
        self.driver.find_element(By.LINK_TEXT, "HOME").click()
        self.driver.find_element(By.LINK_TEXT, "tracker policy").click()
        self.driver.find_element(By.LINK_TEXT, "this website PRIVACY POLICY").click()
        self.driver.find_element(By.LINK_TEXT, "CHART").click()

    def S74(self):
        self.driver.get("http://www.iopblog.org/")
        self.driver.find_element(By.CSS_SELECTOR,
                                 "#generate-slideout-panel > #site-navigation .menu-item-18797 > a").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 "#generate-slideout-panel > #site-navigation .menu-item-18796 > a").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 "#generate-slideout-panel > #site-navigation .menu-item-12195 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".inside-header .header-image").click()
        self.driver.find_element(By.CSS_SELECTOR, ".focus > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".focus > a").click()
        self.driver.find_element(By.LINK_TEXT, "privacy and cookies policy").click()

    def S75(self):
        self.driver.get("http://www.mrmoneymustache.com/")
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-9612 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-9613 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-9611 > a").click()
        self.driver.find_element(By.LINK_TEXT, "MMM Recommends").click()
        self.driver.find_element(By.LINK_TEXT, "Random").click()
        self.driver.find_element(By.LINK_TEXT, "MMM Classics").click()
        self.driver.find_element(By.LINK_TEXT, "Forum").click()
        self.driver.find_element(By.CSS_SELECTOR, ".forumtitle img").click()
        self.driver.find_element(By.CSS_SELECTOR, "#button_login > .firstlevel > .firstlevel").click()
        self.driver.find_element(By.CSS_SELECTOR, "#button_home .last").click()

    def S76(self):
        self.driver.get("https://prezi.com/")
        self.driver.find_element(By.LINK_TEXT, "Product").click()
        self.driver.find_element(By.LINK_TEXT, "Business").click()
        self.driver.find_element(By.LINK_TEXT, "Education").click()
        self.driver.find_element(By.CSS_SELECTOR, ".why-prezi-dropdown").click()
        self.driver.find_element(By.CSS_SELECTOR, ".discover-dropdown").click()
        self.driver.find_element(By.LINK_TEXT, "Pricing").click()
        self.driver.find_element(By.LINK_TEXT, "Basic").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-logo").click()
        self.driver.find_element(By.ID, "how-it-works-top-cta").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-logo").click()
        self.driver.find_element(By.LINK_TEXT, "Education").click()
        self.driver.find_element(By.LINK_TEXT, "Get started").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-logo").click()
        self.driver.find_element(By.LINK_TEXT, "See the science behind Prezi →").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-logo").click()

    def S77(self):
        self.driver.get("https://www.symantec.com/")
        self.driver.find_element(By.LINK_TEXT, "Solutions").click()
        self.driver.find_element(By.LINK_TEXT, "Products & Services").click()
        self.driver.find_element(By.LINK_TEXT, "Support Center").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-logo--image").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "Blogs").click()
        self.vars["win4621"] = self.wait_for_window(2000)
        self.driver.find_element(By.CSS_SELECTOR, ".header-logo").click()

    def S78(self):
        self.driver.get("https://www.thestar.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(2) .c-button__label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(1) .c-button__label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(4) .c-button__label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(5) .c-button__label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(7) .c-button__label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(8) .c-button__label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-main-menu-list__item:nth-child(9) .c-button__label").click()

    def S79(self):
        self.driver.get("https://www.tmz.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".nav-desktop__item:nth-child(1) > .nav-desktop__link").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-desktop__item:nth-child(2) > .nav-desktop__link").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-desktop__item:nth-child(4) > .nav-desktop__link").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".nav-desktop__item:nth-child(5) > .nav-desktop__link").click()
        self.vars["win169"] = self.wait_for_window(2000)

    def S80(self):
        self.driver.get("https://www.bodybuilding.com/")
        self.driver.find_element(By.ID, "header__site-nav--desktop__nav2018Store").click()
        self.driver.find_element(By.ID, "header__site-nav--desktop__nav2018Article").click()
        self.driver.find_element(By.ID, "header__site-nav--desktop__nav2018WorkoutPlans").click()
        self.driver.find_element(By.ID, "header__site-nav--desktop__nav2018Comm").click()
        self.driver.find_element(By.CSS_SELECTOR, ".Icon-bbcom").click()
        self.driver.find_element(By.LINK_TEXT, "Protein").click()
        self.driver.find_element(By.CSS_SELECTOR, ".Icon-bbcom").click()
        self.driver.find_element(By.LINK_TEXT, "Help Center").click()
        self.driver.find_element(By.ID, "header__site-nav--desktop__nav2018WorkoutPlans").click()
        self.driver.find_element(By.LINK_TEXT, "Email Support").click()

    def S81(self):
        self.driver.get("https://www.history.com/")
        self.driver.find_element(By.CSS_SELECTOR, ".header-links > li:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-links > li:nth-child(2) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".m-header--logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-links > li:nth-child(3) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-links > li:nth-child(4) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".m-header--logo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".profile-section-content:nth-child(2) > .register").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header-links > li:nth-child(5) > a").click()

    def S82(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.NAME, "q").send_keys("denver nugets")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("nikola jokic")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.LINK_TEXT, "Images")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Images").click()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").click()
        element = self.driver.find_element(By.NAME, "q")
        actions = ActionChains(driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("milos teodosic")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "All").click()
        self.driver.find_element(By.CSS_SELECTOR, "#pnnext > span:nth-child(2)").click()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").click()
        element = self.driver.find_element(By.NAME, "q")
        actions = ActionChains(driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("paja i jare")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "Images").click()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").click()
        element = self.driver.find_element(By.NAME, "q")
        actions = ActionChains(driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("gole zene")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "All").click()

    def S83(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.NAME, "q").send_keys("kurir.rs")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c2 > a > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".hLogo > img").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".user-profile-link:nth-child(1) > svg").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.ID, "login_email").click()
        self.driver.find_element(By.ID, "login_email").send_keys("websitestests1313@gmail.com")
        self.driver.find_element(By.ID, "login_password").click()
        self.driver.find_element(By.ID, "login_password").send_keys("test1313")
        self.driver.find_element(By.ID, "login-button").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".c12 > a > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".hLogo > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".user-profile-link:nth-child(1) > img").click()
        element = self.driver.find_element(By.LINK_TEXT, "Profil")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "Izloguj se").click()

    def S84(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.NAME, "q").send_keys("blic.rs")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".login__top > a").click()
        self.vars["win6065"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win6065"])
        self.driver.find_element(By.ID, "f_login").send_keys("websitestests1313")
        element = self.driver.find_element(By.ID, "f_password")
        actions = ActionChains(driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.ID, "f_login")
        actions = ActionChains(driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".formContainer > ul:nth-child(1)").click()
        self.driver.find_element(By.ID, "f_login").click()
        self.driver.find_element(By.ID, "f_login").send_keys("websitestests1313@gmail.com")
        element = self.driver.find_element(By.ID, "f_password")
        actions = ActionChains(driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".perm")
        actions = ActionChains(driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".formContainer > ul:nth-child(1)").click()
        self.driver.find_element(By.ID, "f_password").send_keys("test1313")
        self.driver.find_element(By.CSS_SELECTOR, ".loginButton").click()
        self.driver.find_element(By.ID, "f_password").send_keys("test")
        self.driver.find_element(By.LINK_TEXT, "Registruj se").click()
        self.driver.find_element(By.ID, "f_login").click()
        self.driver.find_element(By.ID, "f_login").send_keys("websitestests1313@gmail.com")
        self.driver.find_element(By.ID, "f_password").click()
        self.driver.find_element(By.ID, "f_password").send_keys("test1313")
        self.driver.find_element(By.ID, "f_confirmPassword").click()
        self.driver.find_element(By.ID, "f_confirmPassword").send_keys("test1313")
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()

    def S85(self):
        self.driver.get("https://www.sportvision.rs/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.CSS_SELECTOR, ".login-btn > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".login-btn > span")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "login_email").click()
        self.driver.find_element(By.ID, "login_email").send_keys("websitestests1313@gmail.com")
        self.driver.find_element(By.ID, "login_password").click()
        self.driver.find_element(By.ID, "login_password").send_keys("test1313")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-login > span:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".slider_menu_mens > a > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".slider_zene_drop_down > a > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".block > a > .img-responsive").click()
        self.driver.find_element(By.LINK_TEXT, "Odjava").click()

    def S86(self):
        self.driver.get("https://www.signmeup.com/#!/default")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.CSS_SELECTOR, ".nav > li:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".m-r-sm").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn > strong").click()
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtLogin").click()
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtLogin").send_keys("pajaijare")
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtPassword").click()
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtPassword").send_keys("test1313")
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_btnSignOn").click()
        self.driver.find_element(By.CSS_SELECTOR, "a > img").click()
        self.driver.find_element(By.LINK_TEXT, "Sign in").click()
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtLogin").click()
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtLogin").send_keys("pajaijare")
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtPassword").click()
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_txtPassword").send_keys("test1313")
        self.driver.find_element(By.ID, "Smubody1_mnuBody_ucBLogin1_btnSignOn").click()
        self.driver.find_element(By.CSS_SELECTOR, "nobr").click()

    def S87(self):
        self.driver.get("https://www.playboy.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.execute_script("window.scrollTo(0,3000)")
        self.driver.execute_script("window.scrollTo(0,3367)")
        self.driver.find_element(By.CSS_SELECTOR, ".icon-account-out").click()
        self.driver.find_element(By.ID, "username").send_keys("websitestests1313@gmail.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("test1313")
        self.driver.find_element(By.ID, "loginBtn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".icon-account").click()
        self.driver.find_element(By.LINK_TEXT, "Log Out").click()

    def S88(self):
        self.driver.get("http://liveleaks.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.ID, "dk5").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "Liveleaks.com").click()
        self.vars["win3926"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win3926"])
        self.driver.find_element(By.NAME, "s").click()
        self.driver.find_element(By.NAME, "s").send_keys("kim kardasian")
        self.driver.find_element(By.CSS_SELECTOR, ".srchBtn").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "Liveleaks.com").click()
        self.vars["win8108"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win8108"])
        self.driver.find_element(By.ID, "dk6").click()
        self.driver.find_element(By.NAME, "s").click()
        self.driver.find_element(By.NAME, "s").send_keys("boston")
        self.driver.find_element(By.NAME, "s").send_keys(Keys.ENTER)
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "Liveleaks.com").click()
        self.vars["win8261"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win8261"])

    def S89(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("srbija")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.LINK_TEXT, "Stanovništvo")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.LINK_TEXT, "Images")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Images").click()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").click()
        element = self.driver.find_element(By.NAME, "q")
        actions = ActionChains(driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("amerika")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "All").click()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").click()
        element = self.driver.find_element(By.NAME, "q")
        actions = ActionChains(driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("mondo.rs")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".g > div > div > .rc .LC20lb").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav_sport > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav_info > a").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".nav_zabava > a")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".nav_zabava > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logo-img").click()

    def S90(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(1280, 738)
        self.driver.find_element(By.NAME, "q").send_keys("mojauto.rs")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb").click()
        self.driver.find_element(By.CSS_SELECTOR, "#filter_quarter_202 > input:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#filter_quarter_202 > input:nth-child(2)").send_keys("opel")
        self.driver.find_element(By.CSS_SELECTOR, "#filter_quarter_202 > input:nth-child(2)").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "filter_count_num").click()
        self.driver.find_element(By.CSS_SELECTOR, "#filter_quarter_288 > input:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#filter_quarter_288 > input:nth-child(2)").send_keys("beograd")
        self.driver.find_element(By.ID, "filter_count_href").click()
        self.driver.find_element(By.ID, "filter_basic_max_210").click()
        self.driver.find_element(By.ID, "filter_basic_max_210").send_keys("100000")
        self.driver.find_element(By.ID, "advert_filter_basic_container").click()
        self.driver.find_element(By.ID, "filter_basic_max_211").click()
        self.driver.find_element(By.ID, "filter_basic_max_211").send_keys("2034")
        element = self.driver.find_element(By.ID, "filter_count_num")
        actions = ActionChains(driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.ID, "filterBlock")
        actions = ActionChains(driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.ID, "advert_filter_basic_container").click()
        self.driver.find_element(By.CSS_SELECTOR, ".headLogo > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".noR_Bor > #ajax_login").click()

    def S91(self):
        self.driver.get("http://blog.b92.net/")
        self.driver.find_element(By.ID, "reg_user").click()
        self.driver.find_element(By.ID, "reg_user").send_keys("testertester")
        self.driver.find_element(By.ID, "reg_pass").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".submit-btn:nth-child(7)")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "reg_pass").send_keys("testtest123")
        self.driver.find_element(By.CSS_SELECTOR, ".submit-btn:nth-child(7)").click()
        self.driver.find_element(By.LINK_TEXT, "Najnovije").click()
        self.driver.find_element(By.LINK_TEXT, "Najčitanije").click()
        self.driver.find_element(By.LINK_TEXT, "Komentari").click()
        self.driver.find_element(By.LINK_TEXT, "Preporuke").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".novi > a")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text:nth-child(3)").click()
        self.driver.find_element(By.LINK_TEXT, "odjava").click()

    def S92(self):
        self.driver.get("https://www.maxi.rs//SRB_rs")
        self.driver.find_element(By.LINK_TEXT, "Prijava").click()
        self.driver.find_element(By.ID, "login_email").click()
        self.driver.find_element(By.ID, "login_email").send_keys("testiranjesajta199@gmail.com")
        self.driver.find_element(By.ID, "login_password").send_keys("testtest123")
        self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .pull-left").click()
        self.driver.find_element(By.CSS_SELECTOR, ".slider_14:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".slider_14:nth-child(2) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".slider_14:nth-child(3) > a").click()
        self.driver.find_element(By.LINK_TEXT, "OUTLET").click()
        self.driver.find_element(By.CSS_SELECTOR, ".jordan-main-menu > a").click()
        self.driver.find_element(By.LINK_TEXT, "Odjava").click()

    def S93(self):
        self.driver.get("https://www.djaksport.com/")
        self.driver.set_window_size(1920, 1032)
        element = self.driver.find_element(By.ID, "ctl06_ctl11_lblPrijava")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "ctl06_ctl11_txtLoginEmail").click()
        self.driver.find_element(By.ID, "ctl06_ctl11_txtLoginEmail").send_keys("testiranjesajta199@gmail.com")
        self.driver.find_element(By.ID, "ctl06_ctl11_txtLoginPassword").click()
        self.driver.find_element(By.ID, "ctl06_ctl11_txtLoginPassword").send_keys("testtest123")
        self.driver.find_element(By.ID, "ctl06_ctl11_btnLogin").click()
        element = self.driver.find_element(By.ID, "ctl06_ctl00_menu_ctl00_plainName")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "ctl06_ctl00_menu_ctl00_plainName").click()
        self.driver.find_element(By.ID, "ctl06_ctl01_menu_ctl01_plainName").click()
        element = self.driver.find_element(By.ID, "ctl06_ctl01_menu_ctl06_plainName")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "ctl06_ctl01_menu_ctl06_plainName").click()
        self.driver.find_element(By.ID, "ctl06_ctl01_menu_ctl07_plainName").click()
        self.driver.find_element(By.ID, "ctl06_ctl02_menu_ctl08_plainName").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".dropdown-form > a")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "ctl06_ctl09_linkNotUser").click()

    def S94(self):
        self.driver.get("https://www.goodreads.com/")
        self.driver.find_element(By.ID, "userSignInFormEmail").click()
        self.driver.find_element(By.ID, "logo").click()
        self.driver.find_element(By.ID, "userSignInFormEmail").send_keys("testiranjesajta199@gmail.com")
        self.driver.find_element(By.ID, "user_password").click()
        self.driver.find_element(By.ID, "user_password").send_keys("testtest123")
        self.driver.find_element(By.CSS_SELECTOR, ".gr-button--dark").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "My Books").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".siteHeader__primaryNavInline .primaryNavMenu--siteHeaderBrowseMenu > .primaryNavMenu__trigger > span").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".siteHeader__primaryNavInline .siteHeader__topLevelItem--community span").click()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("game of thrones")
        self.driver.find_element(By.CSS_SELECTOR, ".searchBox__icon--magnifyingGlass").click()
        self.driver.find_element(By.CSS_SELECTOR, ".stacked > div:nth-child(3)").click()
        self.driver.find_element(By.ID, "search_field_title").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dropdown__trigger .circularIcon").click()
        self.driver.find_element(By.LINK_TEXT, "Sign out").click()

    def S95(self):
        self.driver.get("https://www.idea.rs/online/#!/")
        self.driver.find_element(By.LINK_TEXT, "Prijava").click()
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .has-error > div").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("testiranjesajta199@gmail.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("testtest123")
        self.driver.find_element(By.NAME, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-icon").click()
        self.driver.find_element(By.CSS_SELECTOR, ".news-icon path:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".action-icon path:nth-child(4)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".favorit-icon > p").click()
        self.driver.find_element(By.CSS_SELECTOR, ".list-icon > p").click()
        self.driver.find_element(By.ID, "kako-kupovati").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-icon > p").click()
        self.driver.find_element(By.LINK_TEXT, "testiranjesajta199@gmail.com").click()
        self.driver.find_element(By.CSS_SELECTOR, ".osobni-podaci > a:nth-child(3)").click()

    def S96(self):
        self.driver.get("https://www.maxi.rs//grad/beograd")
        self.driver.find_element(By.LINK_TEXT, "Prijavi se").click()
        self.driver.find_element(By.NAME, "login-email").click()
        self.driver.find_element(By.NAME, "login-email").send_keys("testiranjesajta@gmail.com")
        self.driver.find_element(By.NAME, "login-password").click()
        self.driver.find_element(By.NAME, "login-password").send_keys("testtest123")
        self.driver.find_element(By.CSS_SELECTOR, ".dialog-alt-links:nth-child(10)").click()
        self.driver.find_element(By.NAME, "login-submit").click()
        self.driver.find_element(By.LINK_TEXT, "Najveći popusti").click()
        self.driver.find_element(By.LINK_TEXT, "Usluge").click()
        self.driver.find_element(By.LINK_TEXT, "Lepota").click()
        self.driver.find_element(By.LINK_TEXT, "Putovanja").click()
        self.driver.find_element(By.CSS_SELECTOR, "body").click()
        self.driver.find_element(By.LINK_TEXT, "Odjavi se").click()

    def S97(self):
        self.driver.get("https://www.maxi.rs/")
        self.driver.set_window_size(1920, 1032)
        self.driver.find_element(By.CSS_SELECTOR, ".hidden-sm").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("branislavzoric87@gmail.com")
        self.driver.find_element(By.ID, "password-current").send_keys("Lokosi100!")
        self.driver.find_element(By.CSS_SELECTOR, ".js-login-submit").click()
        self.driver.find_element(By.LINK_TEXT, "Online prodavnica").click()
        self.driver.find_element(By.LINK_TEXT, "Moji spiskovi").click()
        self.driver.find_element(By.LINK_TEXT, "Moji spiskovi").click()
        self.driver.find_element(By.LINK_TEXT, "Moji spiskovi").click()
        self.driver.find_element(By.LINK_TEXT, "Promocije").click()
        self.driver.find_element(By.LINK_TEXT, "Naši brendovi").click()
        self.driver.find_element(By.LINK_TEXT, "Inspiracija").click()
        self.driver.find_element(By.LINK_TEXT, "Recepti").click()
        element = self.driver.find_element(By.LINK_TEXT, "O kompaniji")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "O kompaniji").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(By.CSS_SELECTOR,
                                           ".component-row:nth-child(1) > .component:nth-child(1) .image")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".hidden-sm").click()
        self.driver.find_element(By.LINK_TEXT, "Odjavi se").click()

    def S98(self):
        self.driver.get(
            "https://www.polovniautomobili.com/auto-oglasi/pretraga?brand=alfa-romeo&model%5B%5D=33&model%5B%5D=75&model%5B%5D=145&model%5B%5D=146&model%5B%5D=147&model%5B%5D=155&model%5B%5D=156&model%5B%5D=156-crosswagon&model%5B%5D=159&model%5B%5D=164&model%5B%5D=166&model%5B%5D=brera&model%5B%5D=giulia&model%5B%5D=giulietta&model%5B%5D=gt&model%5B%5D=gtv&model%5B%5D=mito&model%5B%5D=spider&model%5B%5D=stelvio&model%5B%5D=ostalo&price_to=3000&year_from=&year_to=2019&region%5B%5D=Beograd&showOldNew=all&submit_1=&without_price=1")
        self.driver.set_window_size(1920, 1047)
        element = self.driver.find_element(By.CSS_SELECTOR, ".uk-float-left:nth-child(2) > span")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Prijavi se").click()
        self.driver.find_element(By.ID, "username_header").click()
        self.driver.find_element(By.ID, "username_header").send_keys("testiranjesajta199@gmail.com")
        self.driver.find_element(By.ID, "next-step").click()
        self.driver.find_element(By.ID, "password_header").click()
        self.driver.find_element(By.ID, "password_header").send_keys("testtest123")
        self.driver.find_element(By.NAME, "login").click()
        self.driver.find_element(By.LINK_TEXT, "BRZA PRETRAGA").click()
        self.driver.find_element(By.LINK_TEXT, "Najnoviji oglasi").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sumo_brand span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sumo_brand .opt:nth-child(2)").click()
        self.driver.find_element(By.ID, "price_to").click()
        self.driver.find_element(By.ID, "price_to").send_keys("3000")
        self.driver.find_element(By.CSS_SELECTOR, ".sumo_year_to > .CaptionCont > label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sumo_year_to .opt:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sumo_city span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sumo_city .opt:nth-child(2) > label").click()
        self.driver.find_element(By.ID, "submit_1").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".uk-float-left:nth-child(2)")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Odjavi se").click()

    def S99(self):
        self.driver.get("https://www.sportske.net/")
        self.driver.find_element(By.LINK_TEXT, "Prijavi se").click()
        self.driver.find_element(By.ID, "dbEmail").click()
        self.driver.find_element(By.ID, "dbEmail").send_keys("testiranjesajta199@gmail.com")
        self.driver.find_element(By.ID, "dbPassword").click()
        self.driver.find_element(By.ID, "dbPassword").send_keys("lokosi10")
        self.driver.find_element(By.ID, "btnRemember").click()
        self.driver.find_element(By.NAME, "userLogin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-menu-list > li:nth-child(1) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-menu-list > li:nth-child(2) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-menu-list > li:nth-child(3) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-menu-list > li:nth-child(4) > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main-menu-list > li:nth-child(5) > a").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".sub-menu-list > li:nth-child(6) > a")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-gear").click()
        self.driver.find_element(By.LINK_TEXT, "Odjavi se").click()

    def S100(self):
        self.driver.get("https://trefsport.com/")
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "username").click()
        self.driver.find_element(By.ID, "username").send_keys("testertester")
        self.driver.find_element(By.ID, "password").send_keys("testtest123")
        self.driver.find_element(By.ID, "login-form").click()
        self.driver.find_element(By.ID, "_submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(2) > li:nth-child(1) > .linkable").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(2) > li:nth-child(2) > .linkable").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(2) > li:nth-child(3) > .linkable").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(2) > li:nth-child(4) > .linkable").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(2) > li:nth-child(5) > .linkable").click()
        self.driver.find_element(By.LINK_TEXT, "Logout").click()




